### ISSUE TITLE
Small gaps and discontinuites between tiles

### ISSUE THREAD

**Issue by gvellut** [opensciencemap/vtm#119]
I have cloned the vTM project today and set up the vtm-android-examples project on my device (Nexus 10, Android 4.4.2). I have launched the SampleMapActivity from the menu.

I see gaps (white lines) between the tiles. Most of the times it is only when I move (pan or rotate) the map but it also happens when the map is not moving, like on the screenshot below:

![gap1](https://cloud.githubusercontent.com/assets/3685/4808705/e3e2bb68-5ea3-11e4-9940-0ecfe5d17287.png)

Maybe it is a related issue but I also see discontinuities for linear features (roads) at the border of the tiles. See screenshots below.

![gap2](https://cloud.githubusercontent.com/assets/3685/4808708/eb50144a-5ea3-11e4-8d17-ff0de4bf375a.png)

![gap3](https://cloud.githubusercontent.com/assets/3685/4808709/ee23cbee-5ea3-11e4-9ae0-1b64a6b39b1d.png)

**Comment by hjanetzek** [comment]
the original issue should be fixed now
