### ISSUE TITLE
vtm - added points disappear when changing map position at the zoom 19

### ISSUE THREAD

**Issue by Bezzu** [opensciencemap/vtm#144]
Hi,
my app  extends a MapActivity, the map has two VectorTileLayer:
- the base map loaded from a map file
- a layer that shows points and lines.

When I change the map position at the zoom 19 only the points appear and disappear continuously (as in fugures below). 
![screenshot_2015-02-27-11-42-19](https://cloud.githubusercontent.com/assets/5656682/6411288/59271990-be77-11e4-838a-d9d01696b667.png)
![screenshot_2015-02-27-11-42-24](https://cloud.githubusercontent.com/assets/5656682/6411290/5e589ec0-be77-11e4-9e3d-8aedb222cab5.png)

I think that this issue is caused by the high density of points to show.
Has someone already encountered this problem?
Can someone help me?

Thanks in advance.

**Comment by Bezzu** [comment]
Hi everyone,
I have resolved this issue changing the "indices" variable in the "TextItem" class from short to int. The problem was caused by an overflow of this variable when the items associated with a texture are numerous.

**Comment by hjanetzek** [comment]
Thank you!
