### ISSUE TITLE
More theme examples. Suburb names?

### ISSUE THREAD

**Issue by deviousgeek** [opensciencemap/vtm#170]
Does the maintainer (or anyone else) have some more theme examples? I'm looking for a way to add suburb names (like on Google Maps / attached).

Thanks!

![2016-03-24-131426_1300x853_scrot](https://cloud.githubusercontent.com/assets/4342988/14006543/6b8b19d6-f1c2-11e5-9b0f-55c33ddd0e9a.png)

**Comment by dondos** [comment]
There is an exemple in the osmarenderer theme:`<m v="suburb|town|village" zoom-min="10">
        <caption k="name" style="bold" size="15" fill="#000000" stroke="#ffffff" stroke-width="2.0" />
      </m>`

**Comment by hjanetzek** [comment]
@deviousgeek if you are using the OpenScienceMap tiles it should contain most place tags from OSM. Not all features are used by the default style, so you may need to add adittional rules. For a more complete source you can use the Mapzen tiles, which requires a matching stylesheet though:
https://mapzen.com/documentation/vector-tiles/layers/
https://github.com/mapzen/vtm-stylesheet

**Comment by deviousgeek** [comment]
Thanks, got it working beautifully!
