### ISSUE TITLE
Unable to see labels for the geojson file in JeoIndoorMapActivity.java

### ISSUE THREAD

**Issue by akarsh** [opensciencemap/vtm#176]
Hallo,

I am using the JeoIndoorMapActivity.java from the android-example for displaying the geojson file.
Here is the [raw geojson file](https://gist.githubusercontent.com/akarsh/cbdeaa31f647e2851ba9bdb70a0f1ad1/raw/2477b1041297aa4abdc5688276a9bc5d5ac36183/testmap.geojson).

I am unable to show room names i.e. labels in the map.
Here is [code gist file ](https://gist.github.com/1ffc64674b58beb0ea2e8a924b567ed5.git)

Help is appreciated.

Thank you

**Comment by devemux86** [comment]
Development continues at https://github.com/mapsforge/vtm.
