### ISSUE TITLE
Reverse Geocoding Listener

### ISSUE THREAD

**Issue by jvoyatz** [opensciencemap/vtm#177]
Hello all,

It is already implemented in Mapsforge. [Here you can found the saple](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/ReverseGeocodeViewer.java).

This feature shows to user info regarding POI or Ways in a radius.

**Comment by devemux86** [comment]
Could you create the issue in https://github.com/mapsforge/vtm where VTM development continues?

**Comment by jvoyatz** [comment]
Oh my god. I was in hurry and i didn't see i posted here.
