### ISSUE TITLE
Add InfoWindow

### ISSUE THREAD

**Issue by ghost** [opensciencemap/vtm#179]
Hi guys,

I am having a lot of trouble adding an info window in the "onItemSingleTapUp" event. Is there any open source project that uses vtm that does it? I searched for it but didn't find it. Can anyone point me in the right direction regarding this?

Thanks!

**Comment by devemux86** [comment]
**Development continues at https://github.com/mapsforge/vtm**

For questions please use the Discussions: https://github.com/mapsforge/vtm/discussions
