### ISSUE TITLE
Gradle build crash sometimes

### ISSUE THREAD

**Issue by hanchao** [opensciencemap/vtm#57]
Sometime OutOfMemoryError, or like this
![image](https://cloud.githubusercontent.com/assets/1942091/2565934/6c0d7fb6-b8bc-11e3-8d88-2b435a841331.png)

Seems memory leak.  I'm not sure .then the error will be

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been stopped, killed or may have crashed)
```

**Comment by ZhyneAmenodin** [comment]
Thanks, it helped a lot.
